### ISSUE TITLE
Default settings persist

### ISSUE THREAD

**Issue by Taxit0m** [tfonteyn/Sshd4a#8]
I like the lightweight design while still retaining customization.  Unfortunately for me, I don't know if it's my device, or user error, but besides the toggle switches no matter what changes I make to the settings page they remain unaltered.  The service is not running when I try to make changes to the user defined settings like setting a username and password, specifying which port to listen on, etc.  I tried looking for a config file to edit, doesn't seem to exist.  There's no built in module to create a public or private key, there's no way to create a new key and when trying to choose not to use the key at all and make use of different login credentials the values are never set and remain unchanged.  
  I really hope I'm wrong and that its user error on my end, and there's something I'm doing or not doing correctly.  If it's not user error or device incompatibility I fear what I've stumbled upon is an app that creates shells on the users device the developer has access to with no way of removing the developers built in entryway with full network control, all files access, start on boot and remote start on external intent....  
     Pardon my French, but I don't know, let's call a spade a spade here; if it looks like a duck, quacks like a duck, and waddles like duck, I'm calling it a duck......  The shoe fits.  
   I know I must be doing something wrong, please tell me what it is and where I'm making the error.

**Comment by tfonteyn** [comment]
hehe - my first conspiracy-theory issue.

First some answers, then below troubleshooting.

> I don't know if it's my device, or user error

At the minimum, please let me know:
- Android version ? (or alternative rom/OS version)
- optionally which brand/model (purely out of interest)
- is the device rooted? This app does NOT use/need rooting but if rooted, I can point you to the location of the settings file; which is in the default settings folder of the app installation.

> setting a username and password, specifying which port to listen

  Those options are standard dialog-popup which are common to probably 99% of all android app.
  Tap the option, fill in what you want, and tap "ok" to save
  Note that to set a password, the username must be set first. The port (as prompted) must be between 1024 and 32768.

> config file to edit

  Settings are stored in the standard Android Preferences.
 [handled in this source file](https://github.com/tfonteyn/Sshd4a/blob/dev/app/src/main/java/com/hardbacknutter/sshd/SettingsFragment.java)
 
> details on authentication

see the [docs](https://github.com/tfonteyn/Sshd4a/wiki#authentication-methods)

> There's no built in module to create a public or private key

Correct, because this is not needed/wanted. I suggest you read up on how public/private keys work.
A quote from the below linked article:

    The private key is retained by the client and should be kept absolutely secret.
    ...
    The public key is uploaded to a remote server that you want to be able to log into with SSH.

A simple google search will show plenty of articles demonstrating how to do this.
For example: [https://www.digitalocean.com/community/tutorials/how-to-configure-ssh-key-based-authentication-on-a-linux-server](https://www.digitalocean.com/community/tutorials/how-to-configure-ssh-key-based-authentication-on-a-linux-server)

Public keys of clients you wish to trust, are held in a standard "authorized_keys" which can be imported, or directly edited when you login using the single-use password (ssh-copy-id is NOT supported btw)

Typically you would however create (or already have) such a file on the CLIENT. If you have more than one client you want to trust, simply combine the needed keys in a single file before importing.

The "authorized_keys" and other dropbear (see the app's project readme on the main page) which provides the actual ssh services can be found in the default apps "files" directory in the hidden ".dropbear" subdirectory. The dropbear host key and logfiles are there as well. This is where you will find yourself after a login. Be CAREFUL when looking at or diting those.

> make use of different login credentials the values are never set and remain unchanged.

This seems to be your only/real problem.

Troubleshooting:

As mentioned, port/user/pass settings are standard dialog boxes with an "ok"+"cancel" button. If those do not work, then your device is - to say the least - seriously weird.
Please try and explain in detail with screenshots:

1. Stop the service if running (button on the top-taskbar)
2. open the settings
3. scroll to the port number for an easy test.
4. take a screenshot BEFORE tapping on that option.
5. tap the "port" option
6. take a screenshot
7. you should have an input field with the current port number highlighted. Replace/edit and fill in portnumber 2222. There should also be an "ok" button. Tap that.
8. the dialog should close now; take a screenshot.

Upload those screenshots here and we'll take it from there.

**Comment by Taxit0m** [comment]
> hehe - my first conspiracy-theory issue.
> 
> First some answers, then below troubleshooting.
> 
> > I don't know if it's my device, or user error
> 
> At the minimum, please let me know:
> - Android version ? (or alternative rom/OS version)
> - optionally which brand/model (purely out of interest)
> - is the device rooted? This app does NOT use/need rooting but if rooted, I can point you to the location of the settings file; which is in the default settings folder of the app installation.
> 
- Android 12 and 13; 12 on a Nokia c110, 13 on a TCL 40xe 5g.
- neither have root privileges.


> > setting a username and password, specifying which port to listen
> 
>   Those options are standard dialog-popup which are common to probably 99% of all android app.
>   Tap the option, fill in what you want, and tap "ok" to save

- the dialog popups appear, I can input a value, but the parts that are missing for me are buttons.  There is no button for "ok" or "save" or even a "cancel"  button.  Sneaking suspicion here 🤔, may be jumping the starting gun....


>   Note that to set a password, the username must be set first. The port (as prompted) must be between 1024 and 32768.
> 
> > config file to edit
> 
>   Settings are stored in the standard Android Preferences.
>  [handled in this source file](https://github.com/tfonteyn/Sshd4a/blob/dev/app/src/main/java/com/hardbacknutter/sshd/SettingsFragment.java)
>  
> > details on authentication
> 
> see the [docs](https://github.com/tfonteyn/Sshd4a/wiki#authentication-methods)
> 
> > There's no built in module to create a public or private key
> 
> Correct, because this is not needed/wanted. I suggest you read up on how public/private keys work.
> A quote from the below linked article:
> 
>     The private key is retained by the client and should be kept absolutely secret.
>     ...
>     The public key is uploaded to a remote server that you want to be able to log into with SSH.
> 
> A simple google search will show plenty of articles demonstrating how to do this.
> For example: [https://www.digitalocean.com/community/tutorials/how-to-configure-ssh-key-based-authentication-on-a-linux-server](https://www.digitalocean.com/community/tutorials/how-to-configure-ssh-key-based-authentication-on-a-linux-server)
> 
I have used keys in the past, when I was deploying VPS on Amazon's AWS, many moons ago when they were offering infinite instances free for a year as long as you stayed in the micro process tier. ---->> the dashboard automatically generated and supplied your key upon deployment of the process.  So I take my limited knowledge solely from that experience.

> Public keys of clients you wish to trust, are held in a standard "authorized_keys" which can be imported, or directly edited when you login using the single-use password (ssh-copy-id is NOT supported btw)
> 
> Typically you would however create (or already have) such a file on the CLIENT. If you have more than one client you want to trust, simply combine the needed keys in a single file before importing.
> 
> The "authorized_keys" and other dropbear (see the app's project readme on the main page) which provides the actual ssh services can be found in the default apps "files" directory in the hidden ".dropbear" subdirectory. The dropbear host key and logfiles are there as well. This is where you will find yourself after a login. Be CAREFUL when looking at or diting those.
> 
> > make use of different login credentials the values are never set and remain unchanged.
> 
> This seems to be your only/real problem.
> 
> Troubleshooting:
> 
> As mentioned, port/user/pass settings are standard dialog boxes with an "ok"+"cancel" button. If those do not work, then your device is - to say the least - seriously weird.
> Please try and explain in detail with screenshots:
> 
> 1. Stop the service if running (button on the top-taskbar)
> 2. open the settings
> 3. scroll to the port number for an easy test.
> 4. take a screenshot BEFORE tapping on that option.
> 5. tap the "port" option
> 6. take a screenshot
> 7. you should have an input field with the current port number highlighted. Replace/edit and fill in portnumber 2222. There should also be an "ok" button. Tap that.
> 8. the dialog should close now; take a screenshot.
> 
> Upload those screenshots here and we'll take it from there.
>

**Comment by tfonteyn** [comment]
sidenote: the AWS approach is (in a way) less secure. A private key should never leave your machine (client) other then as a backup. i.o.w.: the AWS server side should only ever have the public key of your pub/prv keypair. There are circumstances where BOTH the client and server need a pub/prv keypair but this is outside the current issue. Debating amazon (or similar orgs) is pointless anyhow.

>  the parts that are missing for me are buttons. 

well, that's disturbing. I presume this is the same with the user-name field?
Those fields and dialogs are 100% handled by the Android library (androidx.preference) with near zero interaction with the app code.

The port field does set a "numeric-only" flag, but the username field is as default/basic as it can get.

Are fields like the "Dropbear/Extra Commandline options" behaving the same ?  Don't enter anything in that field, just open the dialog to check if the cancel/ok buttons are there.

Do you have any 'special' software installed that might change other apps UI ?  Skinning software or likewise ? (to be honest I have no clue if such software even exists).

The bottomline is that those settings fields, just like the switches,  are all handled by that android.preference library and not by the app. The only (and far-fetched) thing I can see is that somehow the dialog displayed is cut-off due to screen-size. Try flipping the device from portrait/landscape.

**Comment by Taxit0m** [comment]
> sidenote: the AWS approach is (in a way) less secure. A private key should never leave your machine (client) other then as a backup. i.o.w.: the AWS server side should only ever have the public key of your pub/prv keypair. There are circumstances where BOTH the client and server need a pub/prv keypair but this is outside the current issue. Debating amazon (or similar orgs) is pointless anyhow.
> 

- agreed, even having the key generated by the dashboard and it being the same system that deploys the instance you'd think could or would eventually lead to exploitation.  Just highlighting the fact it was the first time I had ever been introduced to them because that was the only option offered for method of authentication.  The entire dashboard was too complex for what it was managing.  The whole process of your signup, choosing your OS, choosing server locations, staying within the guidelines...  They were also fishing for feedback from users.  There was absolutely zero documentation, nothing was clearly labeled, no install notes, no FAQ, just thrown to the wolves, literally no instructions what so ever unless you made an appointment for a telephone call at $200 per hour, where they required the first whole hour paid for up front before they would set the appointment.  
  I don't know anyone who actually paid for it, through trial and error a group of us on IRC finally figured it out and wrote some half assed documentation on a starting guide full of lots of "i think"s and "I guess"s.  
  Trying to even understand what was going on in the developers heads was like trying to learn brale in Chinese.  Arguing Amazon is moot.


> >  the parts that are missing for me are buttons. 
> 
> well, that's disturbing. I presume this is the same with the user-name field?
> Those fields and dialogs are 100% handled by the Android library (androidx.preference) with near zero interaction with the app code.
> 
> The port field does set a "numeric-only" flag, but the username field is as default/basic as it can get.
> 
> Are fields like the "Dropbear/Extra Commandline options" behaving the same ?  Don't enter anything in that field, just open the dialog to check if the cancel/ok buttons are there.
> 
> Do you have any 'special' software installed that might change other apps UI ?  Skinning software or likewise ? (to be honest I have no clue if such software even exists).
> 
> The bottomline is that those settings fields, just like the switches,  are all handled by that android.preference library and not by the app. The only (and far-fetched) thing I can see is that somehow the dialog displayed is cut-off due to screen-size. Try flipping the device from portrait/landscape.
> 
  
- no special skinning or graphics changes, I tried flipping to landscape and didn't see a change, my first thought also was display size also.  When I get back around those 2 devices later on today I'll get some screen shots for you and see what we can come up with

**Comment by tfonteyn** [comment]
> the parts that are missing for me are buttons.

You'll need to provide screenshots. If you do, I can take this issue to Google, otherwise there is not much I can do. As mentioned, the edit dialogs are fully handled by the Google Android library (androidx.preference).

**Comment by tfonteyn** [comment]
I never heard back from you, but if you're still interested, please try [1.4.0](https://github.com/tfonteyn/Sshd4a/releases/tag/v1.4.0)

I found a potential solution to the missing strings which can be traced back to some OEM vendors not including certain defaults (like the default 'OK' and 'Cancel' texts.). I no longer use those defaults / have internalized them. So with some luck...

closing this issue, but feel free to reopen if needed.

**Comment by tfonteyn** [comment]
finally got to the bottom of this one, now fixed properly
here you go: [1.5.1](https://github.com/tfonteyn/Sshd4a/releases/tag/v1.5.1)
